-- Applied by Spring's SQL initializer today and by Flyway once
-- org.springframework.boot:spring-boot-flyway is on the classpath, so every statement
-- is written to be idempotent.
-- Initial schema for the Unicornt store.
-- PostgreSQL 16. Money amounts are whole CLP units, hence INTEGER instead of NUMERIC.

-- ---------------------------------------------------------------- catalog

CREATE TABLE IF NOT EXISTS product_types (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS products (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(200) NOT NULL,
    product_type_id INTEGER      NOT NULL REFERENCES product_types (id),
    category_id     INTEGER      NOT NULL REFERENCES categories (id),
    price           INTEGER      NOT NULL,
    description     TEXT,
    image_base      VARCHAR(255),
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    stock           INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT products_price_non_negative CHECK (price >= 0),
    CONSTRAINT products_stock_non_negative CHECK (stock >= 0)
);

CREATE INDEX IF NOT EXISTS idx_products_category ON products (category_id);
CREATE INDEX IF NOT EXISTS idx_products_type     ON products (product_type_id);

-- ---------------------------------------------------------------- security

CREATE TABLE IF NOT EXISTS roles (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    email      VARCHAR(150) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS users_roles (
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles (id),
    PRIMARY KEY (user_id, role_id)
);

-- ---------------------------------------------------------------- cart

CREATE TABLE IF NOT EXISTS cart_items (
    id         BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES products (id),
    quantity   INTEGER NOT NULL,
    CONSTRAINT uk_cart_items_user_product UNIQUE (user_id, product_id),
    CONSTRAINT cart_items_quantity_positive CHECK (quantity > 0)
);

-- ---------------------------------------------------------------- addresses

CREATE TABLE IF NOT EXISTS addresses (
    id         BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    street     VARCHAR(200) NOT NULL,
    city       VARCHAR(100) NOT NULL,
    region     VARCHAR(100) NOT NULL,
    zip_code   VARCHAR(20),
    is_default BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_addresses_user ON addresses (user_id);

-- ---------------------------------------------------------------- orders

CREATE TABLE IF NOT EXISTS orders (
    id               BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT        NOT NULL REFERENCES users (id),
    address_id       BIGINT        NOT NULL REFERENCES addresses (id),
    shipping_address VARCHAR(300)  NOT NULL,
    total            NUMERIC(12,2) NOT NULL,
    status           VARCHAR(20)   NOT NULL DEFAULT 'CONFIRMED',
    created_at       TIMESTAMP     NOT NULL DEFAULT (NOW() AT TIME ZONE 'UTC'),
    CONSTRAINT orders_total_non_negative CHECK (total >= 0)
);

CREATE INDEX IF NOT EXISTS idx_orders_user ON orders (user_id);

CREATE TABLE IF NOT EXISTS order_items (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT        NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id   INTEGER       NOT NULL REFERENCES products (id),
    product_name VARCHAR(200)  NOT NULL,
    unit_price   NUMERIC(12,2) NOT NULL,
    quantity     INTEGER       NOT NULL,
    subtotal     NUMERIC(12,2) NOT NULL,
    CONSTRAINT order_items_quantity_positive CHECK (quantity > 0)
);

CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items (order_id);
